apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- deployment.yaml
- service.yaml
- post-sync.yaml

images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: 0.2
